AMP_RINKEBY_MATCHING_ENGINE_IP=${AMP_MAINNET_MATCHING_ENGINE_IP:-'x'} \
AMP_MAINNET_CLIENT_IP=${AMP_MAINNET_CLIENT_IP:-'x'} \
AMP_MAINNET_ETHEREUM_IP=${AMP_MAINNET_ETHEREUM_IP:-'x'} \
AMP_MAINNET_EXCHANGE_CONTRACT_ADDRESS=${AMP_MAINNET_EXCHANGE_CONTRACT_ADDRESS} \
AMP_MAINNET_WETH_CONTRACT_ADDRESS=${AMP_MAINNET_WETH_CONTRACT_ADDRESS} \
AMP_MAINNET_FEE_ACCOUNT_ADDRESS=${AMP_MAINNET_FEE_ACCOUNT_ADDRESS} \
AMP_MAINNET_ETHERBASE=${AMP_MAINNET_ETHERBASE} \

echo "Deploying AMP with the following parameters:"
echo -e "Matching Engine IP: ${AMP_MAINNET_MATCHING_ENGINE_IP}"
echo -e "Client IP: ${AMP_MAINNET_CLIENT_IP}"
echo -e "Ethereum IP: ${AMP_MAINNET_ETHEREUM_IP}"
echo -e "Exchange Contract Address: ${AMP_MAINNET_EXCHANGE_CONTRACT_ADDRESS}"
echo -e "WETH Contract Address: ${AMP_MAINNET_WETH_CONTRACT_ADDRESS}"
echo -e "Fee Account Address: ${AMP_MAINNET_FEE_ACCOUNT_ADDRESS}"
echo -e "Rinkeby Etherbase: ${AMP_MAINNET_ETHERBASE}"

docker stack deploy -c docker-compose.production-mainnet.yml amp-production